-- Database structure for Explorer Net (PostgreSQL)
-- Generated from pylib ORM models

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    telephone INTEGER NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    country_code INTEGER NOT NULL,
    reset_password BOOLEAN NOT NULL DEFAULT FALSE,
    remark TEXT,
    verified BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS clients (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    business_name VARCHAR(255) NOT NULL,
    country_code INTEGER NOT NULL,
    telephone INTEGER NOT NULL,
    password VARCHAR(255) NOT NULL,
    remark TEXT,
    verified BOOLEAN NOT NULL DEFAULT FALSE,
    reset_password BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS outlets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country VARCHAR(3) NOT NULL,
    unit VARCHAR(255) NOT NULL,
    address1 VARCHAR(255) NOT NULL,
    address2 VARCHAR(255),
    postcode VARCHAR(32) NOT NULL,
    latitude NUMERIC(10, 7) NOT NULL,
    longitude NUMERIC(10, 7) NOT NULL,
    phone_number INTEGER NOT NULL,
    description TEXT,
    client_id INTEGER NOT NULL REFERENCES clients (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_outlets_client_id ON outlets (client_id);

CREATE TABLE IF NOT EXISTS pages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outlet_id INTEGER NOT NULL REFERENCES outlets (id),
    html TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pages_outlet_id ON pages (outlet_id);

CREATE TABLE IF NOT EXISTS menus (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outlet_id INTEGER NOT NULL REFERENCES outlets (id),
    name VARCHAR(255) NOT NULL,
    price NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL CHECK (currency IN ('USD', 'GBP', 'EUR')),
    category VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_menus_outlet_id ON menus (outlet_id);
